language: python
python:
    - 2.7.8
    - 2.7
    - pypy
    - 3.3
    - 3.4
    - 3.5
    - pypy3

install:
  - pip install -r requirements.txt

services:
  - mongodb

before_script:
  - sudo redis-server /etc/redis/redis.conf --requirepass 'secret'
  - sleep 5
  - cd src
  - python -m tests.load_config
  - sleep 3
  - python runserver.py &
  - sleep 3
  - python ./tests/api_server.py &
  - sleep 3

script:
  - python -m tests.auth
