language: python
python:
    - 2.7.8
    - 2.7
    - pypy
    - 3.3
    - 3.4
    - 3.5
    - pypy-5.3.1

install:
  - pip install -r requirements.txt
  - pip install coveralls

services:
  - mongodb

before_script:
  - sudo redis-server /etc/redis/redis.conf --requirepass 'secret'
  - sleep 3
  - python -m fomalhaut.tests.load_config
  - sleep 3
  - python -m fomalhaut.runserver &
  - sleep 3
  - python -m fomalhaut.tests.api_server &
  - sleep 3

script:
#  - python -m unittest discover -s fomalhaut -p "*_test.py"
  - coverage run --source=fomalhaut -m unittest discover -s fomalhaut -p "*_test.py"

after_success:
  coveralls
